name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check
        run: deno task check

      - name: Build
        run: deno task build
